
import { Project, SiteContent } from './types';

export const PROJECTS: Project[] = [
  {
    "id": "2",
    "title": " Mercedes Benz - G 580",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1GZnRx4e9IYhOefmpGEYNm3MdmRLzrEic",
    "videoUrl": "https://www.youtube.com/embed/eoWZQDbXhSk",
    "client": " Mercedes Benz",
    "director": "INV-FILM",
    "year": "2024",
    "aspectRatio": "16:9",
    "description": "Redefining luxury through architectural lines and silent motion.",
    "gallery": []
  },
  {
    "id": "1",
    "title": "Mercedes-Benz EQS 450",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1fr7CHiEXO7hd9A0UovBGALkKqTCVH1D1",
    "videoUrl": "https://www.youtube.com/embed/kyXIylIX6Ys",
    "client": "Mercedes-Benz",
    "director": "INV-FILM",
    "year": "2024",
    "aspectRatio": "16:9",
    "description": "A global campaign for Samsung Galaxy, focusing on the seamless connection between devices.",
    "gallery": [
      "https://picsum.photos/seed/s1/1200/675",
      "https://picsum.photos/seed/s2/1200/675"
    ]
  },
  {
    "id": "5",
    "title": "Oliveyoung Mag x Health +",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1EpwcUWXF0E6CIqdsMLoOtzRoaL35jspU",
    "videoUrl": "https://www.youtube.com/embed/d52Z1xWGV38",
    "client": "oliveyoung ",
    "director": "INV-FILM",
    "year": "2024",
    "aspectRatio": "9:16",
    "description": "High-speed liquid cinematography in a social-first format.",
    "gallery": [
      "https://picsum.photos/seed/ln1/600/1067"
    ]
  },
  {
    "title": "THE LX [ Solar Control ]",
    "client": "THE LX",
    "director": "INV FILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1RtNxz4ZEgn_y7pYzKaA0YdbOFD4Uojog",
    "videoUrl": "https://www.youtube.com/embed/qPGLKRcmDdA",
    "id": "1767844618432",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "thumbnail": "https://lh3.googleusercontent.com/d/11c1-7jBEQHEupWCLCi0BGHrTGHws4eiW",
    "videoUrl": "https://www.youtube.com/embed/m9VCwiO5-_c",
    "title": "NACIFIC - ATEEZ's Playground ",
    "client": "NACIFIC",
    "director": "INV-Film",
    "year": "2025",
    "id": "1767346485314",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "THE LX [Safety]",
    "client": "THE LX",
    "director": "INV-FILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/12CqxFt-y48JG8t0xikiXFljpzv9WINF0",
    "videoUrl": "https://www.youtube.com/embed/1l3IWbPNIg0",
    "id": "1767844202734",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Bang Bang fall ",
    "client": "Bang Bang",
    "year": "2024",
    "director": "inv film",
    "videoUrl": "https://www.youtube.com/embed/EZKMgEpaiOw",
    "thumbnail": "https://lh3.googleusercontent.com/d/1twk1woMbJDXUj3bm6GuMzR0w3zzl7kFo",
    "id": "1767850236754",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "THE LX  [ Night Vision ] ",
    "client": "THE LX",
    "year": "2025",
    "director": "INV FILM",
    "thumbnail": "https://lh3.googleusercontent.com/d/1WYdiRM5vPA3MzTn5XItvskZGHNXYcutD",
    "videoUrl": "https://www.youtube.com/embed/O_Zaz_kepg0",
    "id": "1767844391124",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "NACIFIC - ATEEZ's PARTY NIGHT",
    "client": "NACIFIC ",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1oBdraO6vNMSiLI20k7CXGSBc6Jo3LSPv",
    "videoUrl": "https://www.youtube.com/embed/jyOQangdYEc",
    "category": "BRANDED CONTENT",
    "id": "1767346851057",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "id": "3",
    "title": "Oliveyoung Mag x Health +",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1vsWzx4e4n-bo4hsHqAGxRjVRvG-MZOQP",
    "videoUrl": "https://www.youtube.com/embed/HzTRyUm6Sk0",
    "client": "Oliveyoung",
    "director": "KIM SEONG-MIN",
    "year": "2024",
    "aspectRatio": "9:16",
    "description": "A vertical series exploring the science of skincare.",
    "gallery": [
      "https://picsum.photos/seed/ae1/600/1067"
    ]
  },
  {
    "videoUrl": "https://www.youtube.com/embed/3UIEJ0EiSWg",
    "title": "Oliveyoung Mag x Health +",
    "client": "Oliveyoung Mag",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Ej8KkM1rlk4eAeZaO3Ekvd-S1SXjEEWz",
    "aspectRatio": "9:16",
    "id": "1767333802030",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "director": "INV-FILM",
    "year": "2026",
    "description": ""
  },
  {
    "title": "The boiboy Kim young dae",
    "client": "The boiboy",
    "director": "inv film",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/19str2ETaymlAYTxZ8z1h82fX2ZthOrV-",
    "videoUrl": "https://www.youtube.com/embed/DxafxFinNYc",
    "id": "1767848547245",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Dancer - Taeyeon",
    "client": "Dancer - Taeyeon",
    "director": "INV - FILM",
    "year": "2022",
    "thumbnail": "https://lh3.googleusercontent.com/d/1MU--Fm7iR74jp7lymx034uqcQW8LBMIj",
    "videoUrl": "https://www.youtube.com/embed/c_T_V3NUQfw",
    "id": "1769746568455",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Bang Bang summer",
    "client": "Bang Ban",
    "director": "inv film",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/EKwxVZs_vbE",
    "thumbnail": "https://lh3.googleusercontent.com/d/1XfvPlnR7ANBAZUI3JSh-7S9KXM70lD4x",
    "id": "1767848792798",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "id": "6",
    "title": "CGV X SAMYANG Hot chicken cup rice",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/17nMvWPz4N1sjNrZZ4WlXSOuC4uOqyKd7",
    "videoUrl": "https://www.youtube.com/embed/jzfdJcMKG4c",
    "client": "CGV X SAMYANG",
    "director": "LEE JAE-HOON",
    "year": "2023",
    "aspectRatio": "16:9",
    "description": "Behind the scenes of the digital infrastructure that powers the nation.",
    "gallery": [
      "https://picsum.photos/seed/sk1/1200/675"
    ]
  },
  {
    "title": "CJ BIBIGO",
    "client": "CJ",
    "director": "INV FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1YHUMeY-XYfCWNOe3Y5ImCLj3ozVPrkg2",
    "videoUrl": "https://vimeo.com/517749243?fl=pl&fe=sh",
    "aspectRatio": "16:9",
    "id": "1767846879739",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "description": ""
  },
  {
    "title": "CGV - 짜장팝콘",
    "videoUrl": "https://www.youtube.com/embed/5XyRz1j6ec8",
    "director": "inv-film",
    "year": "2025",
    "client": "CGV",
    "thumbnail": "https://lh3.googleusercontent.com/d/1vwu0Onclho86r3YbX1ZcCCGRSoMA7lSw",
    "id": "1767347588974",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "CJ BIBIGO KIMCHI",
    "thumbnail": "https://lh3.googleusercontent.com/d/1wUQhhp53AwCPB835hrJqTVMVTnoKd-UE",
    "client": "CJ BIBIGO",
    "director": "INV FILM",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/xOiam-YMQyU",
    "id": "1767847532693",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "TOP10 MAN",
    "client": "TOP10",
    "director": "INV FILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1yCUz65J_HVF9QLTI9n9DmrsWWWRUK7uc",
    "videoUrl": "https://www.youtube.com/embed/DrdUaCwl-A4",
    "id": "1767846287390",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Seoul Auction MODERN & CONTEMRIC ART",
    "client": "Seoul Auction",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/oSb-ZdYTIQc",
    "category": "INTERVIEW",
    "aspectRatio": "9:16",
    "thumbnail": "https://lh3.googleusercontent.com/d/1mMqOV_doCuyrlfO85f-lYCqL33Rh5Ytp",
    "id": "1769752391517",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "Noblesses Korea x JONS - 정수영 작가",
    "client": "Noblesses Korea ",
    "year": "2023",
    "videoUrl": "https://www.youtube.com/embed/qACMqGC9FYw",
    "aspectRatio": "9:16",
    "thumbnail": "https://lh3.googleusercontent.com/d/1jFyIvPN9eDplIhvnItWtZJ93l0vRFmnE",
    "category": "INTERVIEW",
    "id": "1769754005487",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "FUJIFILM - JU JI HUN",
    "client": "FUJIFILM",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/58vARkpKEsc",
    "category": "INTERVIEW",
    "thumbnail": "https://lh3.googleusercontent.com/d/1oozndLgozndti0w5ZOBR1oFQKVElMd7q",
    "id": "1769753019543",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "스타일디거 - THE PROTRAIT OF LADY",
    "client": "스타일디거 ",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1DEoigDv-J-Uiezc4swWGVM4-TfyRivEr",
    "videoUrl": "https://www.youtube.com/embed/XIluM1DXfNI",
    "category": "INTERVIEW",
    "id": "1769753518145",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "thumbnail": "https://lh3.googleusercontent.com/d/1e-7Iri64NKoDEc1pgCwD62DWcOP6Dv9o",
    "title": "top10 S.O.M",
    "client": "top10",
    "director": "inventoryfilm",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/X-bP96J2jU8",
    "id": "1767850538615",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/gPswFdZQfeg",
    "thumbnail": "https://lh3.googleusercontent.com/d/1H0PJX4nR5kCmYSFj_ZbFGXMLGcza4s6K",
    "title": "i key ",
    "client": "i key",
    "year": "2024",
    "director": "inv film",
    "id": "1767851322349",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/uL62KMh4PfM",
    "title": "TOP10 - SHIRT SERIES WOMAN SUMMER",
    "client": "TOP10",
    "thumbnail": "https://lh3.googleusercontent.com/d/11p9RpVMtkkzgDWSR1OV-J9OtzG2H0d-K",
    "aspectRatio": "16:9",
    "id": "1767334362481",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "director": "INV-FILM",
    "year": "2026",
    "description": ""
  },
  {
    "title": "VIPIX Medical",
    "client": "VIPIX Medical",
    "director": "inv film",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/baFsM7obbos",
    "thumbnail": "https://lh3.googleusercontent.com/d/1MJD75pad_GZINQ8_JpaGN9zpTB9Gsqkd",
    "id": "1767851573288",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Noblesse Korea x JONS - 김선영 대표",
    "client": "Noblesse Korea",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/RC59HPADihU",
    "thumbnail": "https://lh3.googleusercontent.com/d/12p8Nq43uwn18fN7yqxcjKLL-90q-sLeB",
    "category": "INTERVIEW",
    "aspectRatio": "9:16",
    "id": "1769754157546",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": " SEOUL AUCTION - Docent LEE CHANGYONG",
    "videoUrl": "https://www.youtube.com/embed/l674YlqGnwI",
    "client": "SEOUL AUCTION",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/10F6sxRowu5pdUz_bbrmDgVmtqLpp717f",
    "aspectRatio": "9:16",
    "id": "1769752863441",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": " 대교 - \"I RAISE YOU\"",
    "client": " 대교",
    "year": "2023",
    "videoUrl": "https://www.youtube.com/embed/F5c4e_61AM0",
    "thumbnail": "https://lh3.googleusercontent.com/d/1GkiZKNQehmpk29gb0Uox_0vakRqBk5VD",
    "category": "INTERVIEW",
    "id": "1769752607960",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/y5E7oJTD0-g",
    "thumbnail": "https://lh3.googleusercontent.com/d/16oWrM0hUrMUw6X8Z6273UOGz34_OEaIe",
    "director": "inv film",
    "title": "top10 Korea",
    "client": "top10",
    "year": "2024",
    "id": "1767850866692",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Yellow light - Furniture Brand",
    "client": "Yellow light",
    "director": "INV -FILM",
    "year": "2021",
    "thumbnail": "https://lh3.googleusercontent.com/d/1oNC2IwSNU9wS6knT886ue0hAOD7wrFlx",
    "videoUrl": "https://www.youtube.com/embed/_wqQU69_qsQ",
    "aspectRatio": "16:9",
    "id": "1769746279054",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Yellow light - Furniture Master Craftsman",
    "client": "Yellow light",
    "director": "INV - FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1m_fRZfp8RyTlN1M8NPZEDx_hB1DjWZ7x",
    "videoUrl": "https://www.youtube.com/embed/bnSr4NVAtU8",
    "id": "1769746108986",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Vintage Rolex - UNCLE ROLEX",
    "client": "UNCLE ROLEX",
    "director": "INV-VILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1SFfjATOWcFwwlh0OSh4jWLI262c1A4ru",
    "videoUrl": "https://www.youtube.com/embed/Kdv_klDH6Dw",
    "id": "1767347296147",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "BREKE AMBITION x 27RING x TAK PSM MV",
    "client": "BREKE AMBITION x 27RING x TAK",
    "director": "INV film",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/aM1_S1HNv1s",
    "thumbnail": "https://lh3.googleusercontent.com/d/1AQhNOAqOGa2aoq8USETHTpSJLAMUYyA9",
    "id": "1767852277186",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "NEWBALACE KIDS",
    "client": "NEWBALACE KIDS",
    "director": "inv film",
    "thumbnail": "https://lh3.googleusercontent.com/d/1TGjzECoW5ChxhZ7aVKJxDKfnoolZpAaq",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/HHWyC6ryAtE",
    "id": "1767852850042",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Sony Korea - 작가 송철의",
    "client": "Sony Korea",
    "year": "2023",
    "videoUrl": "https://www.youtube.com/embed/lgfbDkbx1a4",
    "category": "INTERVIEW",
    "thumbnail": "https://lh3.googleusercontent.com/d/14SYu26S-qX2xOrTu_Ln85HJn30ySUVoD",
    "id": "1769753327143",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "THE LX 배우 김영대 ",
    "client": "THE LX",
    "director": "INV - FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1xl_Fx7NSDDssJwrt_xnfcDoafu_e9Nn-",
    "videoUrl": "https://www.youtube.com/embed/XlqKLZvPcZM",
    "id": "1769745944919",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "id": "7",
    "title": "Pantofola d'Oro 1886",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://lh3.googleusercontent.com/d/1i9ukGXrSh6XDaU-Edmlt49zI1yDDp1k0",
    "videoUrl": "https://www.youtube.com/embed/l18U0qSFoaA",
    "client": "Pantofola d'Oro 1886",
    "director": "INV-FILM",
    "year": "2025",
    "aspectRatio": "16:9",
    "description": "A study of machine-generated architecture.",
    "gallery": [
      "https://picsum.photos/seed/am1/1200/675"
    ]
  },
  {
    "title": "oliveyoung mag vol37",
    "client": "oliveyoung",
    "director": "inv film",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/v2mVdqmk3WE",
    "thumbnail": "https://lh3.googleusercontent.com/d/1aF_VXgR1oTZRnrluBvLsxTRmIM9dz9gT",
    "aspectRatio": "9:16",
    "id": "1767849979401",
    "category": "BRANDED CONTENT",
    "gallery": [],
    "description": ""
  },
  {
    "director": "inv film",
    "client": "담따프레시",
    "title": "담따프레시 정준호",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/KG6vIGtaGhw",
    "thumbnail": "https://lh3.googleusercontent.com/d/1xqokwk-F2soGqYYkHtHW-xekG4G0zUpq",
    "id": "1767851882557",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/F0gpCnCBOBk",
    "thumbnail": "https://lh3.googleusercontent.com/d/13TkCqVjioBBY2SvzoCwL5nHMqST0JYYT",
    "title": "100YEARS SHOP Rabbit & Turtle",
    "client": "백년화편",
    "director": "INV FILM",
    "year": "2024",
    "id": "1767847807927",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "thumbnail": "https://lh3.googleusercontent.com/d/1yYFkz6hAWTHl1iJH_taTXC0XwFReLZxI",
    "title": "100Years shop Rabbit",
    "client": "백년화편",
    "director": "INV FILM",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/4zYldlAiQtw",
    "id": "1767848027433",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "100years shop turtle",
    "client": "백년화편",
    "director": "INV FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1OVjc5uKac4faGjM9a6KajGR4iH9_0Jv5",
    "videoUrl": "https://www.youtube.com/embed/QCfNQi-aBG4",
    "id": "1767848232735",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "THE LX 배우 정재영",
    "client": "THE LX ",
    "director": "INV - FILM",
    "year": "2022",
    "videoUrl": "https://www.youtube.com/embed/fwAU9HnAFac",
    "thumbnail": "https://lh3.googleusercontent.com/d/1aM0n4Ui3Un-k2IyWX6r13gYS50q32ZfG",
    "id": "1769745739690",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/4f7CuWribQY",
    "title": "YEzac - 김창옥",
    "client": "yezac",
    "director": "INV-FILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1i1MGMaYavmWhVaUnrRvF9LQxZRuGa5wg",
    "id": "1767340012171",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/VdpYNUkVFcI",
    "thumbnail": "https://lh3.googleusercontent.com/d/1XBanR15zziGvFdmhGWtjjmRb4fNrsfAz",
    "title": "NACIFIC - ATEEZ's Universe",
    "client": "NACIFIC",
    "year": "2025",
    "director": "INV-FILM",
    "category": "MAKING",
    "id": "1767346245406",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "year": "2025",
    "director": "INV-FILM",
    "videoUrl": "https://www.youtube.com/embed/GF1HvNeydQo",
    "thumbnail": "https://lh3.googleusercontent.com/d/1HflAa1b0BT8xAbIxOwnrP-X08k80FBta",
    "title": "YElLLOW mattress",
    "client": "YElLLOW light",
    "id": "1767338981151",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "id": "4",
    "title": "HYUNDAI - THE IONIQ WAY",
    "category": "BRANDED CONTENT",
    "thumbnail": "https://images.unsplash.com/photo-1605142859862-978be7eba909?q=80&w=1470&auto=format&fit=crop",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "client": "HYUNDAI",
    "director": "INV-FILM",
    "year": "2023",
    "aspectRatio": "16:9",
    "description": "The journey towards a sustainable future of mobility.",
    "gallery": [
      "https://picsum.photos/seed/h1/1200/675"
    ]
  },
  {
    "thumbnail": "https://lh3.googleusercontent.com/d/1R5ZT3MhBB4JtgQxSJyBgQLRI3Ey1uJNR",
    "title": "VITRO",
    "client": "VITRO",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/1oUFvB7dRZo",
    "director": "INV-FILM",
    "id": "1767843752995",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "BRIDGESTONE GOLF",
    "thumbnail": "https://lh3.googleusercontent.com/d/19lW6i6dATROrNNATXbIAXTDOHx1FM7tI",
    "client": "BRIDGESTONE",
    "year": "2024",
    "director": "INV FILM",
    "videoUrl": "https://www.youtube.com/embed/Z0qTxjxAJ94",
    "id": "1767847300811",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "NORDISK JEJU",
    "client": "NORDISK",
    "director": "INV FILM",
    "thumbnail": "https://lh3.googleusercontent.com/d/1DmYrOt32shiKZYYzu8x8mo9ml6LUtHCH",
    "videoUrl": "https://www.youtube.com/embed/SmnATQ-QbRA",
    "id": "1767846650939",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "year": "2026",
    "description": ""
  },
  {
    "title": "ALLO & LIGH ",
    "client": "ALLO & LIGH",
    "director": "INV - FILM",
    "year": "2023",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Zbzt5Lrqnj8cGWuKQmx2Yddc0fRsgS_4",
    "videoUrl": "https://www.youtube.com/embed/PVq4BSMJ-EY",
    "id": "1769744737077",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/60K5Uudldyc",
    "title": "MimiReve",
    "client": "MimiReve",
    "director": "INV - FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/12mL9YsA13KWT3c4VWijbjyLnupHuFkH6",
    "id": "1769744901691",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "ZARMOI ",
    "client": "ZARMOI ",
    "director": "INV - FILM",
    "year": "2023",
    "thumbnail": "https://lh3.googleusercontent.com/d/1sWLZpbtwj0_ejupZ2s0DTWJscHdQij4v",
    "videoUrl": "https://www.youtube.com/embed/yFkgBjH_9S8",
    "id": "1769745066133",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "VIRGANA",
    "client": "VIRGANA ",
    "director": "INV - FILM",
    "year": "2023",
    "videoUrl": "https://www.youtube.com/embed/nwcbPSYg3gg",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Kny4RuMwGYlO4Pal9lx4khjS_UM1TliC",
    "id": "1769748959209",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "VITRO - Brand",
    "client": "VITRO",
    "director": "INV - FILM",
    "year": "2021",
    "thumbnail": "https://lh3.googleusercontent.com/d/1qEGHTXIhCTKLDv3etIUgzMJq9fLvH7Pr",
    "videoUrl": "https://www.youtube.com/embed/uRQKsWqFl0M",
    "id": "1769746444502",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "SEOUL ACTION - 우향 박래현",
    "client": "SEOUL ACTION ",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/1U13dWXUQ44",
    "category": "INTERVIEW",
    "thumbnail": "https://lh3.googleusercontent.com/d/1RwqA5bM15r8TVRNlGH31lN01mltVvvH-",
    "aspectRatio": "9:16",
    "id": "1769751132451",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "GANA ART 고암 시대를 보다",
    "client": "GANA ART",
    "year": "2025",
    "category": "INTERVIEW",
    "videoUrl": "https://www.youtube.com/embed/68T6WBSgz24",
    "thumbnail": "https://lh3.googleusercontent.com/d/1YgUzqKqRoZUSfqECmCreCemVttD3rmDM",
    "id": "1769752077714",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "GANA ART - 고암 인간을보다",
    "client": "GANA ART",
    "director": "INV-FILM",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/BaUVQejDMpU",
    "thumbnail": "https://lh3.googleusercontent.com/d/1JVNkCLT6IVw30scQ_PATDYtesOFT7Amj",
    "category": "INTERVIEW",
    "id": "1769751854210",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "BRAKE AMBITION X BOBBT F",
    "client": "BRAKE AMBITION X BOBBT F",
    "director": "INV - FILM",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/7xXMl-avOII",
    "thumbnail": "https://lh3.googleusercontent.com/d/1c5bO5nr1NY9cVO4DyaRy6wRZK4L6IGZO",
    "id": "1769746712477",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "CHIUP MATE WOMEN SHORT VER B",
    "client": "CHIUP MATE ",
    "director": "INV - FILM",
    "year": "2022",
    "thumbnail": "https://lh3.googleusercontent.com/d/1kl-gpkZP-wx0GPXSClKLPGpkpS8Mc9GJ",
    "videoUrl": "https://www.youtube.com/embed/Bn3tpHqrGvo",
    "id": "1769745232245",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "SEOUL ACTION - Pablo Picasso",
    "client": "SEOUL ACTION ",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/0DBIIMFqqUs",
    "thumbnail": "https://lh3.googleusercontent.com/d/1eXAZJTM50xYvzuDbc_m-aQyaJpPZ24uj",
    "category": "INTERVIEW",
    "aspectRatio": "9:16",
    "id": "1769753743493",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "thumbnail": "https://lh3.googleusercontent.com/d/1OG7kVXMS_3cyYmP6tOEBDQEB36B-gTJB",
    "title": "CHIUP MATE WOMEN SHORT VER A",
    "client": "CHIUP MATE ",
    "director": "INV - FILM",
    "year": "2022",
    "videoUrl": "https://www.youtube.com/embed/r-j4w69AHXI",
    "id": "1769745399529",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "CHIUP MATE WOMAN PART ",
    "client": "CHIUP MATE",
    "director": "INV - FILM",
    "year": "2022",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Xi65xegHiMZdaqZHDJdjD-gb9PL3KEoe",
    "videoUrl": "https://www.youtube.com/embed/fFHS-9B5oEA",
    "id": "1769745576860",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Skechers Korea Energy",
    "client": "Skechers Korea ",
    "director": "INV - FILM",
    "year": "2021",
    "thumbnail": "https://lh3.googleusercontent.com/d/1_5wlbZCeDEewyZzqebj-EvZkC580pM5T",
    "videoUrl": "https://vimeo.com/525583934?fl=pl&fe=sh",
    "id": "1769747222496",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Fashion Profile - Ji Hoon Kim",
    "client": "Fashion Profile - Ji Hoon Kim",
    "director": "INV - FILM",
    "year": "2023",
    "thumbnail": "https://lh3.googleusercontent.com/d/1U_xI0ced7ct-no2C1IhRrzpUJxc94SKB",
    "videoUrl": "https://www.youtube.com/embed/t1fubGtzKvo",
    "id": "1769746949703",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Yellow light - Brand film",
    "client": "Yellow light ",
    "year": "2021",
    "director": "INV - FILM",
    "videoUrl": "https://www.youtube.com/embed/4WbOPceaMgk",
    "thumbnail": "https://lh3.googleusercontent.com/d/1ci_AgqF48QvnTrNQYwB3cvHHGGAcdgvH",
    "id": "1769748835499",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Food Truck Festival In Korea",
    "client": "Food Truck Festival In Korea",
    "director": "INV- FILM",
    "year": "2018",
    "videoUrl": "https://vimeo.com/298338028?fl=pl&fe=sh",
    "thumbnail": "https://lh3.googleusercontent.com/d/1w03PSoyw9M98PiHiazZwmqU1iScDSouA",
    "id": "1769747824010",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "ANDURO BIKE - 이남기 선수",
    "client": "ANDURO BIKE - 이남기 선수",
    "director": "INV - FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1ahfATPddQSHAL4HDj9tMnHycYu7eIsdG",
    "videoUrl": "https://www.youtube.com/embed/9UKHjVLQIS4",
    "id": "1769746829877",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "Fashion Film - Mdel SO RA CHOI",
    "client": "Fashion PROFILE ",
    "director": "INV - FILM",
    "year": "2020",
    "thumbnail": "https://lh3.googleusercontent.com/d/1lqyub9H10l3lAJ5zFVPYn-sKVzycDRRp",
    "videoUrl": "https://www.youtube.com/embed/mNyLBlLpSbI",
    "id": "1769749689787",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "China Town in Korea",
    "client": "China Town",
    "director": "INV - FILM",
    "videoUrl": "https://www.youtube.com/embed/uP3CGVTqrik",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1rG4tAtF7OeHSMy3tt-gVb0BVwdCO7EOh",
    "id": "1769754408484",
    "aspectRatio": "16:9",
    "gallery": [],
    "year": "2026",
    "description": ""
  },
  {
    "title": "Boxer Shin Dong Myung",
    "client": "Boxer Shin Dong Myung",
    "director": "INV-FILM",
    "videoUrl": "https://www.youtube.com/embed/m6cFDbvsZG4",
    "thumbnail": "https://lh3.googleusercontent.com/d/11E_I8Nj7-MvfHefkglF8-yM6M8Hghg7K",
    "id": "1769750337975",
    "category": "INTERVIEW",
    "aspectRatio": "16:9",
    "gallery": [],
    "year": "2026",
    "description": ""
  },
  {
    "title": "Parkour - Kim ji ho",
    "client": "Parkour - Kim ji ho",
    "videoUrl": "https://www.youtube.com/embed/uSB4KB8dARA",
    "thumbnail": "https://lh3.googleusercontent.com/d/16_m8HUnlLaPlSO5ZCBmWfoPVdaT65afk",
    "category": "INTERVIEW",
    "id": "1769750508213",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "year": "2026",
    "description": ""
  },
  {
    "title": "MUGU - GEUN BYEONG LEE",
    "videoUrl": "https://www.youtube.com/embed/mrQ2pD9c8JY",
    "client": "MUGU - GEUN BYEONG LEE",
    "thumbnail": "https://lh3.googleusercontent.com/d/1UYH4dM-7K3RdPrzvPRJq-KRyMZPISA92",
    "id": "1769750732413",
    "category": "INTERVIEW",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "year": "2026",
    "description": ""
  },
  {
    "title": "Gana Art - 우제길 작가",
    "client": "Gana Art ",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/sVuT1VCah1U",
    "thumbnail": "https://lh3.googleusercontent.com/d/15hFSi2jodg7v-SGB8DB0xlHXM336HGaw",
    "category": "INTERVIEW",
    "id": "1769750957015",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/XBV8c-v97vw",
    "category": "MAKING",
    "title": "Musical School of Rock X Benz",
    "client": "Musical School of Rock X Benz",
    "director": "INV - FILM",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Y_PHO_v3Uk2SNGVdny9JFDmN0iwX-c-z",
    "id": "1769840050864",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "한국관광공사 -Korea Beauty Festival",
    "client": "한국관광공사",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/5dLYAB9bXfY",
    "thumbnail": "https://lh3.googleusercontent.com/d/1rcZpT18wP3C4Y4fs08jVrk1CgeymT4kr",
    "category": "MAKING",
    "id": "1769756325312",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "한국관광공사 - Vietnam E-Sports Fam tour DAY 3",
    "client": "한국관광공사 ",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/k7-jexAUSxE",
    "category": "MAKING",
    "aspectRatio": "16:9",
    "thumbnail": "https://lh3.googleusercontent.com/d/1KU6aZlvLoWPisNs_C_62l73ylk8eV1Xm",
    "id": "1769756166031",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "한국관광공사 - Vietnam E-Sports Fam tour",
    "client": "한국관광공사",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/Sh5McK5Uzc8",
    "thumbnail": "https://lh3.googleusercontent.com/d/1JCm74K5Ieicuf8fJK25ePsSlDS_Awqh2",
    "category": "MAKING",
    "id": "1769755706383",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "브리지스톤 사랑나눔 골브대회",
    "client": "브리지스톤",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/ltd4Cet37qU",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1z_ipbAULeJR2tm7wjx-HHdrGU6eRMKA8",
    "id": "1769756483045",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "BRIDGESTONE GOLF -  박현경 프로 ",
    "client": "BRIDGESTONE",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/Jeh8ytvLPmk",
    "thumbnail": "https://lh3.googleusercontent.com/d/1rM8K8bES87LXCu30z-aO59nXuwDpxOm2",
    "category": "INTERVIEW",
    "id": "1769751450672",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "Gana Art - 장 마리아 작가",
    "client": "Gana Art",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/HfGb_25jd8c",
    "thumbnail": "https://lh3.googleusercontent.com/d/1jANpiG2qMv38JUd_3sLceG-LKqHOHMfT",
    "id": "1769751625886",
    "category": "INTERVIEW",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "Lotte cinema Colorium ",
    "client": "Lotte cinema ",
    "director": "INV - FILM",
    "year": "2023",
    "thumbnail": "https://lh3.googleusercontent.com/d/1FjNDomXyLEg-a2PaeDc7KcVwp_Aiqn1w",
    "videoUrl": "https://www.youtube.com/embed/ce0mCR8iNqs",
    "id": "1769749556076",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "12& - Jewellery",
    "client": "12& ",
    "director": "INV - FILM",
    "year": "2020",
    "thumbnail": "https://lh3.googleusercontent.com/d/1y3BQQgl8Q6W4wNg1DsNeGa5wlfTbvn22",
    "videoUrl": "https://vimeo.com/518039128?fl=pl&fe=sh",
    "id": "1769749836072",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "범맥주",
    "client": "범맥주 ",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/o-_1GOy1MkI",
    "thumbnail": "https://lh3.googleusercontent.com/d/1jVOHYEijke7D6ycett-7mFBDB4bb1cFZ",
    "category": "MAKING",
    "id": "1769755250744",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "도른계",
    "client": "도른계",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/XAm5JxqvNQk",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1mqr0_PXNnU3Xge7JTg6Fi1JiryT0RF4T",
    "id": "1769755399176",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "ZARMOI - BAG",
    "client": "ZARMOI ",
    "director": "INV - FILM",
    "year": "2021",
    "videoUrl": "https://vimeo.com/518045590?fl=pl&fe=sh",
    "thumbnail": "https://lh3.googleusercontent.com/d/1bvfBiGjb_WYhiOCaHcZj9BNnx-r54raG",
    "id": "1769749991694",
    "category": "BRANDED CONTENT",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "videoUrl": "https://www.youtube.com/embed/MbhH1uBppMk",
    "category": "MAKING",
    "title": "YANOLJA",
    "client": "YANOLJA",
    "year": "2025",
    "thumbnail": "https://lh3.googleusercontent.com/d/15GY1ex1EkyM05_CU7oJp30Z-7FuQGNLa",
    "id": "1769754949025",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "YANOLJA",
    "client": "YANOLJA",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/3RGtEuGkDuA",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1haHDp6fBdf0B38rFOCd6f-tVe_0-G0ib",
    "id": "1769754795875",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "테르메덴",
    "client": "테르메덴",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/UMAuL-xIOvI",
    "thumbnail": "https://lh3.googleusercontent.com/d/1jLHNqGuzeluMC0no2RIfKW5Nv9ZotN4x",
    "category": "MAKING",
    "id": "1769754573882",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "Evian",
    "client": "Evian",
    "director": "INV - FILM",
    "year": "2024",
    "thumbnail": "https://lh3.googleusercontent.com/d/1Z0dlpcHAfh_1YlpW6CXZGOPVaGqLgYek",
    "category": "MAKING",
    "videoUrl": "https://www.youtube.com/embed/NDnaUUMZf1k",
    "id": "1769839834558",
    "aspectRatio": "16:9",
    "gallery": [],
    "description": ""
  },
  {
    "title": "NACIFIC X ATEEZ Our Story",
    "client": "NACIFIC ",
    "videoUrl": "https://www.youtube.com/embed/XrUmCcbHyRk",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1NvbtwDgQKonanS_T85Qk1KqoKXGTM4KG",
    "id": "1769777700737",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "year": "2026",
    "description": ""
  },
  {
    "title": "NACIFIC X ATEEZ The Masterpiece",
    "client": "NACIFIC",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/82OjEtZM5hk",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1BH4OGU9i40fcbiXi1OMz2V9Cdv5UCdWF",
    "id": "1769777847031",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "NACIFIC - ATEEZ's Playground",
    "client": "NACIFIC",
    "year": "2024",
    "videoUrl": "https://www.youtube.com/embed/gfg2nA9ExyQ",
    "category": "MAKING",
    "thumbnail": "https://lh3.googleusercontent.com/d/1RREf7mTIM-RZm07zYZjpPCGtZ9I9XgC7",
    "id": "1769777570371",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  },
  {
    "title": "NACIFIC - ATEEZ's PARTY NIGHT",
    "client": "NACIFIC",
    "year": "2025",
    "videoUrl": "https://www.youtube.com/embed/jyOQangdYEc",
    "thumbnail": "https://lh3.googleusercontent.com/d/1O6AvHCi1Jj7VkjzqTBFXmysQmpwb7Glx",
    "id": "1769839680987",
    "category": "MAKING",
    "aspectRatio": "16:9",
    "gallery": [],
    "director": "INV-FILM",
    "description": ""
  }
];

export const DEFAULT_SITE_CONTENT: SiteContent = {
  "directors": {
    "name": "JUNG",
    "subName": "JUNE",
    "manifesto": "WE DON'T JUST RECORD MOMENTS. WE INVENTORY THE ESSENCE OF HUMAN EMOTION THROUGH LIGHT AND SHADOW.",
    "processTitle": "Process",
    "processDesc": "Jung June operates at the intersection of cinematic tradition and digital evolution. His process involves a rigorous deconstruction of brand DNA.",
    "techTitle": "Technology",
    "techDesc": "Utilizing state-of-the-art optical tools and proprietary AI-driven pre-visualization, he bridges the gap between imagination and reality.",
    "disciplines": [
      "Cinematic Storytelling",
      "Automotive Art",
      "Luxury Branding",
      "Abstract Narratives",
      "AI-Enhanced Vision",
      "Futuristic Minimalism"
    ],
    "stats": [
      {
        "label": "Years of Excellence",
        "value": "12+"
      },
      {
        "label": "Campaign Deliveries",
        "value": "500"
      },
      {
        "label": "Innovation",
        "value": "∞"
      },
      {
        "label": "Vision",
        "value": "ONE"
      }
    ]
  },
  "about": {
    "headline": "WE CRAFT VISUAL NARRATIVES FOR THE BOLD.",
    "description1": "Founded with the vision to bridge the gap between commercial efficiency and cinematic art, INV-FILM has become the primary destination for global brands.",
    "description2": "We believe every frame is an inventory of human emotion, technical precision, and cultural zeitgeist. From Samsung to Genesis, our portfolio reflects a commitment to the 'Bold' aesthetic.",
    "img1": "https://images.unsplash.com/photo-1492691523567-6170c81efad1?q=80&w=1470&auto=format&fit=crop",
    "img2": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1470&auto=format&fit=crop",
    "philosophy": "PRECISION IN CHAOS",
    "hub": "SEOUL & BEYOND",
    "innovation": "NEURAL CINEMA LABS"
  }
};
